default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 8cfeb30ba6a7ac9e5bbf1fb5e07b9d3b188a0a362e20b0c6803043dfbee7592ce9e21a0b1871937ddbd989e89f0beb7c38c880eac6dc3d9a4668a85511f8e52d

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

